#!/bin/bash
## Copyright (C) 2021 @Chewy_Mage (Telegram) @Haris131 (Github)
# Author: Chewy(Haris) @Github
# Recode: autorekonek xderm-mini GUI by @ryanfauzy (Facebook and Github)
# Date : 23 Juni 2021
dir=/www/xderm
while true; do
r=$(curl -m50 google.com -w "%{http_code}" --proxy socks5://127.0.0.1:1080 -s -o /dev/null|head -c2);sleep 2
  if [ $r != 30 ]; then
echo -e "Restart Xderm GUI"
cd $dir
./xderm-mini stop
sleep 1
./xderm-mini start
  fi
sleep 1
echo -e "HTTP OK"
done
