#!/bin/bash
# Copyright (C) 2021 @Chewy_Mage (Telegram) @Haris131 (Github)
# Author: Haris131(Haris) @Github
# Recode: autorekonek xderm-mini GUI by @ryanfauzy (Facebook and Github)
# Date : 23 Juni 2021
clear
while true; do
r=$(curl -m50 google.com -w "%{http_code}" --proxy socks5://127.0.0.1:1080 -s -o /dev/null|head -c2);sleep 2
 if [ $r != 30 ]; then
  echo -e "Restart Xderm GUI"
  curl -s http://localhost/xderm/index.php -d 'button1=Stop';sleep 5
  curl -s http://localhost/xderm/index.php -d 'button1=Start';sleep 10
 fi
sleep 1
echo -e "HTTP OK"
done

