#!/bin/bash
# Copyright (C) 2021 @Chewy_Mage (Telegram) @Haris131 (Github)
# Author: Haris131(Haris) @Github
# Recode: autorekonek xderm-mini GUI by @ryanfauzy (Facebook and Github)
# Date : 23 Juni 2021
# Tool Auto Rekonek & Random Config 1-3 xderm GUI"
clear
while true; do
r=$(curl -m50 google.com -w "%{http_code}" --proxy socks5://127.0.0.1:1080 -s -o /dev/null|head -c2);sleep 2
 if [ $r != 30 ]; then
  arr=("1" "2" "3")
  rand=$[$RANDOM % ${#arr[@]}]
  cfg=/www/xderm/config/config
  cat $cfg${arr[$rand]} > /www/xderm/config.txt
  echo -e "Random Config 1 - 3"
  echo -e "Restart Xderm GUI"
  echo Start > /www/xderm/log/st;curl -s http://localhost/xderm/index.php -d 'button1=Start';sleep 4
 fi
sleep 1
echo -e "HTTP OK"
done

